### ISSUE TITLE
Implement RequestForm API

### ISSUE THREAD

**Issue by SundarakrishnanN** [IEEE-RVCE/GateKeeper#19]
Enable  APIs to create a upload a pdf and request for review.. Compute the backend logic as well to decide the heirarchy.

**Comment by ChiragJS** [comment]
Will the user decide the heirarchy or would we store heirarchy as a pre defined template?

**Comment by SundarakrishnanN** [comment]
> Will the user decide the heirarchy or would we store heirarchy as a pre defined template?

it  should automated.. In the future updates we should have an option to customize the hierarchy,however for now,its just automation without any chance of editing.. The database has been designed with scope for such an update in the future(Thats why hierarchy is stored in request form table)

**Comment by SundarakrishnanN** [comment]
Yes, will think on how to split and divide after cies
